### ISSUE TITLE
Auto-levelling is bugged?

### ISSUE THREAD

**Issue by cdutson** [ceryliae/DnDAppFiles#18] opened 2015-04-01 13:48 UTC
Has anyone tried using the auto-leveller in the app? For giggles, I imported the compendium and made a bard. leveled said bard up to 2, and it auto-added abilities.... from the rogue's skill tree. Nothing from the bard's skill tree

I'm not sure if this is a weird data import bug, or if it's the app itself.

I'm aware the people contributing to this may have nothing to do with the app, but I figure if we can make sure it's not the data going into it, than we can file a bug report with the app devs instead.

**Comment by Phied** [comment] 2015-04-01 13:50
I have used it a little bit.  I've done a paladin without issues.  However, when I first installed the app, I had to remove the classes I had created before the last update.  Once I did that and reimported, it worked as intented.  Let me know if that works for you.

**Comment by cdutson** [comment] 2015-04-01 14:11
Still not working correctly. Steps to reproduce:
1. I exported my character, deleted the app, and re-installed it.
2. I have imported the current feats, backgrounds, classes, races, items (mundane), and spells (PHB and EE).
3. I then created a new character: Gnome (Forest), Class: Bard (Valor).
4. I look at my features, and they are now all coming from the wizard class. (spellcasting and arcane recovery, for example).
5. I level up to 2, and use the auto-level feature. Apparently my bard is actually a necromancer.

**Comment by Phied** [comment] 2015-04-01 14:15
Odd.  I do not seem to be having this issue.  I imported the exact same settings you did.  If you look at the class itself in the compendium, what is the bard showing?

**Comment by cdutson** [comment] 2015-04-01 14:17
The compendium content is correct (spells and bard[valor]).

**Comment by cdutson** [comment] 2015-04-01 14:18
Upon further research, it doesn't matter what class I pick, they're all defaulting to the necromancer tree.

The first part (level, hit die, proficiencies, spell ability) are correct, but everything beyond that (number of spells, features) are all necromancer

**Comment by Phied** [comment] 2015-04-01 14:20
Try to delete the necromancer class, then recreate a character.  If that doesn't work, try to delete all of the classes, then try to reimport the file.  I'm going to take a look at the class import just to be sure the file looks ok.  Don't uninstall the app or anything - just delete the classes then reimport.

**Comment by cdutson** [comment] 2015-04-01 14:42
I am deleting each class and trying again using Berserker barbarian as my class. results so far:
- Deleted necromancer: now point to school of arcane
- deleted school of arcane: now points to trickster cleric
- deleted trickster claric: now points to enchantment wizard
- deleted enchant wiz: points to tempest cleric
- deleted tempest cleric: points to knowledge cleric
- deleted knowledge cleric: points to life cleric
- deleted life cleric: points to barbarian (berserker) - yay!

Okay now I try to make my bard:
- create bard (valor): points to berserker barbarian. - damn.
- delete berserker: points to illision wiz
- delete illusion wiz: points to divination wiz
- delete divination wiz: points to devotion pali
- delete devotion pali: points to conjuration wiz
- delete conjuration wiz: points to war cleric
- delete war cleric: points to rogue (arcane)
- delete arcane rogue: points to ancients pali
- delete ancients pali: points to evocation wiz
- delete evocation wiz: points to light cleric
- delete light cleric: points to totem barbarian
- delete totem barbarian: points to death cleric
- delete death cleric: points to vengance pali
- delete vengance pali: points to rogue thief
- delete rogue thief: points to rogue assassin
- delete rogue assassin: points to oathbreaker pali
- delete oathbreaker pali: points to nature cleric
- delete nature cleric: points to transmute wiz
- delete transmute wiz: points to artificer wiz
- delete artificer wiz: points to bart college lore (SO CLOSE)

**Comment by cdutson** [comment] 2015-04-01 14:43
so literally if i delete everything but the class I want, it'll work :P

**Comment by Phied** [comment] 2015-04-01 14:46
Delete every single class.  Then re-import.  There's something in there that is definitely buggy.  Like I said, when I first tried this with the update I had issues as well.  As soon as I cleared out all of the classes in there, and imported, it worked like a dream.  

I literally just now imported the same file without any issue and am able to create your bard.  Once we get you straightened out, I'll email the developer.  I want to be sure we get you fixed first.

**Comment by cdutson** [comment] 2015-04-01 14:54
- Deleted the last two classes. I have zero classes.
- I re-import classes1.2.xml (it successfully adds 28 classes)
- I create a new character (bard - valor)
  result: now I'm an abjuration wizard.

**Comment by cdutson** [comment] 2015-04-01 14:55
Something's up with either the data, or the import. I'm not quite sure what though.

**Comment by ceryliae** [comment] 2015-04-01 14:57
I'm getting the bug too. Tried to autolevel a lore hard from 1 to 2 and got
enchantment wizard

**Comment by Phied** [comment] 2015-04-01 14:58
I'm going to delete all of my classes and reimport.  Is your email up to date on your page cdutson?  I'll send you the bard by itself.

**Comment by ceryliae** [comment] 2015-04-01 14:58
Maybe there's an unclosed autolevel tag somewhere

**Comment by Phied** [comment] 2015-04-01 14:59
No, there isn't.  If there was an unclosed tag it'd fail to import.

**Comment by cdutson** [comment] 2015-04-01 14:59
@Phied Yup, my email is correct.

**Comment by cdutson** [comment] 2015-04-01 15:07
@Phied imported successfully, and levels properly. for giggles, try sending me a couple other classes individually. I'll import them one at a time and see what happens

**Comment by cdutson** [comment] 2015-04-01 15:14
@Phied I imported the paladin you sent. if I try and use it, it's stuck on the bard. same with the ranger and the wizard.

deleted the bard, imported the ranger. now the ranger overrides the wizard. delete the ranger and add the pali. now pali overrides everything. delete the wiz and add the ranger. ranger overrides pali.

**Comment by Phied** [comment] 2015-04-01 15:15
Do you have any old characters from before inside of the app?

**Comment by cdutson** [comment] 2015-04-01 15:16
Nope. like i said, i deleted and reinstalled the app. there's nothing but imported data in it

**Comment by Phied** [comment] 2015-04-01 15:17
Ok.  I'm emailing the dev.  Something is definitely up.  The format follows his template.

**Comment by cdutson** [comment] 2015-04-01 15:18
Cool. I just wanted to make sure.

**Comment by ceryliae** [comment] 2015-04-01 17:03
Did you at some point have a bug where the app crashed and when you loaded that app back up the compendium was empty, and you had to reimport everything?

I had that happen to me, and once that happened, I started having this autoleveling bug.

**Comment by cdutson** [comment] 2015-04-01 17:30
@ceryliae I did not encounter that. That said, I did delete the app and the related data and try from scratch. I still encountered the autolevel bug though.

**Comment by ceryliae** [comment] 2015-04-01 17:31
When you reinstalled the app was it still stuck as rogue?

**Comment by cdutson** [comment] 2015-04-01 17:33
@ceryliae Nope. Once I re-installed, it decided to make me a wizard. You can see the entire history of my debugging in this chain if you read higher up.

**Comment by Phied** [comment] 2015-04-01 17:36
After I was able to re-create the bug on mine, I also was stuck as a wizard.  It seemed to almost always put me as the last class I entered.  Not sure if it's a coincidence or not though.

**Comment by ceryliae** [comment] 2015-04-01 17:54
I got a response from Lion's Den. It's a bug with the app that will be
fixed with the latest update. The problem is not with our files. I will be
closing this issue now.

**Comment by cdutson** [comment] 2015-04-01 17:54
yay! Good to know the data is solid.

**Comment by Phied** [comment] 2015-04-01 17:57
The developer is guessing mid-to late next week for the fix.  It takes a while to get through the Apple store.

**Comment by Phied** [comment] 2015-04-01 19:10
Ok @ceryliae was able to get in touch with the developer.  Here seems to be a temporary workaround until the next update.
- Delete all classes (DO NOT UNINSTALL) - just manually delete all classes.  
- When your classes are blank, create a new class manually called Ranger (Hunter) - make sure you spell it EXACTLY like that.
- Next import the classes file, and choose the option to overwrite existing. (If it doesn't ask to overwrite, you didn't do the previous step correctly.)

Once all of that is finished, you should be able to create a class, and autolevel appropriately.  If you can't, send me an email - it's on my profile here.

**Closed as completed** 2015-04-09 20:03 UTC
Labels: App Developer Bug
